<a href="https://colab.research.google.com/github/sokhan1/PYTHON/blob/main/Organizing_Python_numpy_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



## numpy functions



In [3]:
import numpy as np
A=np.random.randn(3,3) # this code doesn't need tuple
B=np.random.rand(3,3)
print(A)
print(B)
print(A[A[:,0]<0,:]) # boolean index

[[ 0.81438556 -1.79899926 -1.22203563]
 [ 0.40962498  0.16506014 -0.02169802]
 [ 0.39593548  0.10528444 -0.89674283]]
[[0.6236406  0.66088718 0.44383109]
 [0.124782   0.51539514 0.1166275 ]
 [0.63445444 0.88256586 0.34185067]]
[]


In [9]:
A=np.random.randn(3,3)
print(A)
print(np.abs(A))
print(np.sqrt(np.abs(A))) # sqrt need abs
print(np.exp(A))
print(np.log(np.abs(A))) # log needs abs
print(np.log(np.exp(1))) # np.exp(1)=e^1
print(np.log2(2))
# print(np.log3(3)) log3 doesn't exist in python
print(np.round(A))
print(np.round(A,2))
print(np.floor(A))
print(np.ceil(A))

[[ 1.93284318  0.86586139 -1.50731758]
 [-0.14603845  0.12921707  0.47371018]
 [ 0.46773417 -0.14905851  0.349149  ]]
[[1.93284318 0.86586139 1.50731758]
 [0.14603845 0.12921707 0.47371018]
 [0.46773417 0.14905851 0.349149  ]]
[[1.39026731 0.93051673 1.22772863]
 [0.38214977 0.35946776 0.68826607]
 [0.68391094 0.38608096 0.59088832]]
[[6.90912624 2.37705278 0.22150335]
 [0.86412448 1.13793711 1.60594149]
 [1.59637298 0.86151871 1.41786044]]
[[ 0.65899207 -0.14403044  0.41033163]
 [-1.92388536 -2.04626158 -0.74715958]
 [-0.75985516 -1.9034164  -1.0522565 ]]
1.0
1.0
[[ 2.  1. -2.]
 [-0.  0.  0.]
 [ 0. -0.  0.]]
[[ 1.93  0.87 -1.51]
 [-0.15  0.13  0.47]
 [ 0.47 -0.15  0.35]]
[[ 1.  0. -2.]
 [-1.  0.  0.]
 [ 0. -1.  0.]]
[[ 2.  1. -1.]
 [-0.  1.  1.]
 [ 1. -0.  1.]]


In [12]:
print(np.sin(np.pi/6)) # pi needs .np
print(np.cos(np.pi/3))
print(np.tan(np.pi/4))
print(np.tanh(-10))

0.49999999999999994
0.5000000000000001
0.9999999999999999
-0.9999999958776927


In [14]:
np.nan # not a number
#np.log(-1) impossible
print(np.isnan([1,2,np.nan,3,4]))
print(np.isinf([1,2,3,4,np.inf]))


[False False  True False False]
[False False False False  True]


In [23]:
A=np.random.randn(3,4)
print(A)
print(np.max(A))
print(np.max(A,axis=0))
print(np.max(A,axis=1))
print(np.max(A,axis=0, keepdims=True))
print(np.max(A,axis=1,keepdims=True)) # keep dimension
print(np.min(A,axis=0))
print(np.min(A,axis=1))
print(np.argmax(A)) # show us index of the biggest value
print(np.argmax(A,axis=0)) # show us index of the biggest value in each columns
print(np.argmax(A,axis=1)) # show us index of the biggest value in each rows
print(np.argmax(A,axis=1,keepdims=True)) # keep dimension

[[-1.02321554  1.26323916  0.96504177  1.74920702]
 [ 2.11744406 -0.53770099  0.31699313 -0.91307141]
 [-0.12827261 -1.38771523 -1.37154541  0.95968268]]
2.1174440621796546
[2.11744406 1.26323916 0.96504177 1.74920702]
[1.74920702 2.11744406 0.95968268]
[[2.11744406 1.26323916 0.96504177 1.74920702]]
[[1.74920702]
 [2.11744406]
 [0.95968268]]
[-1.02321554 -1.38771523 -1.37154541 -0.91307141]
[-1.02321554 -0.91307141 -1.38771523]
4
[1 0 0 0]
[3 0 3]
[[3]
 [0]
 [3]]


In [26]:
a=np.random.randn(6,1)
print(a)
a_sorted=np.sort(a,axis=0)
print(a_sorted) # in ascending order
print(np.flipud(a_sorted)) # in descending order

[[-0.27732224]
 [-0.26270111]
 [-0.09224746]
 [-0.38948375]
 [-0.11074557]
 [ 0.27731249]]
[[-0.38948375]
 [-0.27732224]
 [-0.26270111]
 [-0.11074557]
 [-0.09224746]
 [ 0.27731249]]
[[ 0.27731249]
 [-0.09224746]
 [-0.11074557]
 [-0.26270111]
 [-0.27732224]
 [-0.38948375]]


In [27]:
A=np.random.randn(3,4)
print(A)
print(np.sum(A))
print(np.sum(A,axis=1))
print(np.sum(A, axis=1, keepdims=True))
print(np.mean(A))
print(np.mean(A, axis=1, keepdims=True))
print(np.std(A)) # standard deviation

[[ 0.61255144  1.02187105  0.1924773   0.65130026]
 [-0.37312229  0.14719333  0.98149342 -0.58567155]
 [-0.95899702 -1.24357384  0.49663219  0.69895376]]
1.6411080566516079
[ 2.47820004  0.16989291 -1.0069849 ]
[[ 2.47820004]
 [ 0.16989291]
 [-1.0069849 ]]
0.13675900472096733


In [37]:
A=np.random.randint(-1,5,size=(12,))
print(A)
print(type(A))
print(A.shape)
B=A.reshape(2,2,3)
print(B)
print(B.ndim) # 3 dimensions

[ 0  1  2  1  3  3  2 -1  3  3  0 -1]
<class 'numpy.ndarray'>
(12,)
[[[ 0  1  2]
  [ 1  3  3]]

 [[ 2 -1  3]
  [ 3  0 -1]]]
3


In [43]:
a=np.array([1,2,3]) # dot product
b=np.array([2,2,1])
a=a.reshape(3,1)
b=b.reshape(3,1)
print(a.transpose()@b) #dot product
print(a.T@b)

A=np.random.randn(4,3,2)
print(A)
print(A.transpose(2,1,0).shape)
print(A.transpose(0,1,2).shape) # change row and column

[[9]]
[[9]]
[[[-0.5466822   0.46363329]
  [-1.71418192  1.80281927]
  [-0.77472427  1.05917539]]

 [[ 0.35112767  0.99264928]
  [ 0.55786624 -0.35950511]
  [-0.01563244  0.04923042]]

 [[-0.40889185 -2.43636384]
  [ 0.30507875  0.24085492]
  [-0.53007187 -0.14683796]]

 [[-0.41092502 -0.21823181]
  [ 0.74192501  2.85323687]
  [ 0.77175986 -0.90387119]]]
(2, 3, 4)
(4, 3, 2)


In [48]:
A=np.arange(20)
print(A)
print(A.reshape(4,5))
print(A.reshape(4,-1)) # automatically column is determined by the number of row
print(A.reshape(2,5,-1).shape)
print(A.reshape(2,-1,5).shape)
print(A.reshape(1,-1)) # 2 dimension row vector
print(A.reshape(-1,1)) # 2 dimension column vector

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
(2, 5, 2)
(2, 2, 5)
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]]
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]]


In [56]:
x=np.random.randn(2,3,4,5,6)
print(x[1,2,:,:,:].shape) # print(x[1,2,:,:,:].shape)=print(x[1,2,...].shape)
print(x[1,2,...].shape)

(4, 5, 6)
(4, 5, 6)


In [62]:
A=np.ones((2,2))
B=np.zeros((2,2))
C=np.hstack([A,B]) # A and B are stacked in horizontal direction
D=np.vstack([A,B]) # A and B are stacked in vertical direction
E=np.block([A,B])
F=np.block([[A],[B]])
G=np.block([[[A]],[[B]]]) # A and B are stacked in depth direction
print(C)
print(D)
print(F)
print(G)
print(G.shape)

[[1. 1. 0. 0.]
 [1. 1. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]]
[[[1. 1.]
  [1. 1.]]

 [[0. 0.]
  [0. 0.]]]
(2, 2, 2)


In [68]:
A = np.random.randn(1,1,1,3,1,1,4,1)
#print(A)
print(A.shape)
print(A.squeeze().shape) # DELETE 1
print(A.squeeze(axis=(0,2,4,5)).shape) # This line can delete only '1' that I want

(1, 1, 1, 3, 1, 1, 4, 1)
(3, 4)
(1, 3, 4, 1)


In [78]:
A=np.random.randn(3,4)
print(A)
print(A.shape)
#A1=A[np.newaxis,....] #np.newaxis is None <- True
A1=np.expand_dims(A,axis=0)
print(A1)
print(A1.shape)
A2=np.expand_dims(A,axis=2)
print(A2)
print(A2.shape)
A3=np.expand_dims(A,axis=1)
print(A3)

[[-0.79398577  0.45085673 -1.15532273  1.22542679]
 [-0.00870169  0.4703996  -1.76535489  0.37449278]
 [-0.7110841  -0.77831863 -0.15183714  0.71298949]]
(3, 4)
[[[-0.79398577  0.45085673 -1.15532273  1.22542679]
  [-0.00870169  0.4703996  -1.76535489  0.37449278]
  [-0.7110841  -0.77831863 -0.15183714  0.71298949]]]
(1, 3, 4)
[[[-0.79398577]
  [ 0.45085673]
  [-1.15532273]
  [ 1.22542679]]

 [[-0.00870169]
  [ 0.4703996 ]
  [-1.76535489]
  [ 0.37449278]]

 [[-0.7110841 ]
  [-0.77831863]
  [-0.15183714]
  [ 0.71298949]]]
(3, 4, 1)
[[[-0.79398577  0.45085673 -1.15532273  1.22542679]]

 [[-0.00870169  0.4703996  -1.76535489  0.37449278]]

 [[-0.7110841  -0.77831863 -0.15183714  0.71298949]]]


In [72]:
A1=np.expand_dims(A,axis=0)
print(A1)
A2=np.expand_dims(A,axis=2)
print(A2)
A3=np.expand_dims(A,axis=1)
print(A3)

[[[ 1.80272593 -0.44476176  2.07677003  0.06486437]
  [-0.57296512  0.17388868  0.5549534   0.49785842]
  [ 0.87958519 -0.4026564   1.0494685   1.16270127]]]
[[[ 1.80272593]
  [-0.44476176]
  [ 2.07677003]
  [ 0.06486437]]

 [[-0.57296512]
  [ 0.17388868]
  [ 0.5549534 ]
  [ 0.49785842]]

 [[ 0.87958519]
  [-0.4026564 ]
  [ 1.0494685 ]
  [ 1.16270127]]]
[[[ 1.80272593 -0.44476176  2.07677003  0.06486437]]

 [[-0.57296512  0.17388868  0.5549534   0.49785842]]

 [[ 0.87958519 -0.4026564   1.0494685   1.16270127]]]
