<a href="https://colab.research.google.com/github/sokhan1/PYTHON/blob/main/Summary_pytorch_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## pytorch is similar to numpy!

In [ ]:
import torch
a=torch.tensor([1,2,3,4])
print(a)
print(type(a))
print(a.dtype) #data type
print(a.shape)
b=torch.tensor([1,2,3.1,4])
print(b.dtype) # data type of each elements

tensor([1, 2, 3, 4])
<class 'torch.Tensor'>
torch.int64
torch.Size([4])
torch.float32


In [ ]:
A = torch.tensor([[1,2],[3,4]]) # Unlike list, the number of elements in each rows must be the same
# A=torch.tensor([[1,2],[3,4,5]])
print(A)
print(A.shape)
print(A.ndim) # the value of dimension
print(A.numel()) # the number of elements

tensor([[1, 2],
        [3, 4]])
torch.Size([2, 2])
2
4


In [ ]:
print(torch.zeros(5))
print(torch.zeros_like(A))
print(torch.ones(5))
print(torch.zeros((3,3))) # Input is tuple
print(torch.arange(3,10,2)) # Basically, it is the same with range, but form is tensor
print(torch.arange(0,1,0.1)) # Decimal point is available
print(torch.linspace(0,1,10)) # Endpoint is not available in Pytorch, Endpoint is only available in Numpy

tensor([0., 0., 0., 0., 0.])
tensor([[0, 0],
        [0, 0]])
tensor([1., 1., 1., 1., 1.])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([3, 5, 7, 9])
tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
        0.9000])
tensor([0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889,
        1.0000])


In [ ]:
a=torch.tensor([1,2,3])
b=torch.tensor([4,5,6])
c=a+b
print(c)

tensor([5, 7, 9])


In [ ]:
A=torch.tensor([[1,2,3],[1,2,3]])
B=torch.tensor([[4,5,6],[1,1,1]])
C=A+B
D=A-B
print(A*B) #(Hadamard product)
print(A/B)
print(B**2)

tensor([[ 4, 10, 18],
        [ 1,  2,  3]])
tensor([[0.2500, 0.4000, 0.5000],
        [1.0000, 2.0000, 3.0000]])
tensor([[16, 25, 36],
        [ 1,  1,  1]])


In [ ]:
A=torch.tensor([[1,2],[3,4]])
B=torch.tensor([[1,2],[3,4]])
print(A@B) # Matrix multiplication

tensor([[ 7, 10],
        [15, 22]])


##Pytorch Index and Slicing

In [ ]:
a=torch.tensor([1,2,3,4,5,6,7,8,9])
print(a[0])
print(a[-1])
print(a[1:4])
print(a[:7])
print(a[:])

tensor(1)
tensor(9)
tensor([2, 3, 4])
tensor([1, 2, 3, 4, 5, 6, 7])
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [ ]:
A=torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(A[0])
print(A[-1])
print(A[1:])
print(A[:])
print(A[0][2])
print(A[0,2])

B=[[1,2,3,4],[5,6,7,8]] #This is list to compare with tensor
print(B)
print(B[0][2])
print(A[1,:])
print(A[1,0:3:2])
print(A[:,2])

tensor([1, 2, 3])
tensor([7, 8, 9])
tensor([[4, 5, 6],
        [7, 8, 9]])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor(3)
tensor(3)
[[1, 2, 3, 4], [5, 6, 7, 8]]
3
tensor([4, 5, 6])
tensor([4, 6])
tensor([3, 6, 9])


In [ ]:
A=torch.tensor([[[0,1,2,3],[4,5,6,7],[8,9,10,11]],[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
print(A)
print(A.shape) # The first element is dimension(depth)
print(A[0,1,2])

a=torch.tensor([[[1,2,3,4]]])
print(a.shape)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]])
torch.Size([2, 3, 4])
tensor(6)
torch.Size([1, 1, 4])


In [ ]:
#Boolean Index
a=[1,2,3,4,5,3,3] #This is list
print(a==3)
A=torch.tensor([[1,2,3,4],[5,3,7,3]])
print(A==3) #This is the equality for tensor
print(A[A==3])
A[A==3]=100 #This is comfortable in comparison to loop
print(A)

A=torch.tensor([[1,2],[3,4],[5,6],[7,8]])
B=torch.tensor([True,False,True,False])
print(A[B,:]) # If A is list, not tensor, it doesn't work

False
tensor([[False, False,  True, False],
        [False,  True, False,  True]])
tensor([3, 3, 3])
tensor([[  1,   2, 100,   4],
        [  5, 100,   7, 100]])
tensor([[1, 2],
        [5, 6]])


In [ ]:
a=torch.tensor([1,2,3,4,5])
A=a[2]
print(A)

A=a[torch.tensor(2)]
print(A)

A=a[torch.tensor([2,3,4])]
print(A)

A=a[torch.tensor([[2,2,2],[3,3,3]])]
print(A)

a=torch.tensor([[1,2,3],[4,5,6]])
print(a[0])
A=a[torch.tensor([[0,1],[1,1]])]
print(A.shape)
print(A)

tensor(3)
tensor(3)
tensor([3, 4, 5])
tensor([[3, 3, 3],
        [4, 4, 4]])
tensor([1, 2, 3])
torch.Size([2, 2, 3])
tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[4, 5, 6],
         [4, 5, 6]]])


In [ ]:
A=torch.tensor([[1,2],[3,4],[5,6],[7,8]])
print(A)
print(A.shape)

print(A[0,1])

print(A[torch.tensor([[False,True],[False,False],[False,False],[False,False]])])
print(A[A==2])

print(A[[True,False,False,True],[False,True]])

print(A[torch.tensor([1,1,2,2,2])])

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
torch.Size([4, 2])
tensor(2)
tensor([2])
tensor([2])
tensor([2, 8])
tensor([[3, 4],
        [3, 4],
        [5, 6],
        [5, 6],
        [5, 6]])


## Functions of Pytorch

In [ ]:
A=torch.randn(3,3) # n=normal
B=torch.rand(3,3) # uniform
print(A)
print(B)
print(A[A[:,0]<0,:]) # Only when the first component is negative

tensor([[ 1.1600, -0.3928, -0.1850],
        [ 1.6343,  0.6014,  0.8529],
        [-0.8097, -0.1778,  0.4325]])
tensor([[0.4796, 0.2659, 0.1437],
        [0.0734, 0.0357, 0.1200],
        [0.8685, 0.3435, 0.1190]])
tensor([[-0.8097, -0.1778,  0.4325]])


In [ ]:
A=torch.randn(3,3)
print(A)
print(torch.abs(A))
print(torch.sqrt(torch.abs(A)))
print(torch.exp(A))
print(torch.log(torch.abs(A)))
print(torch.log(torch.exp(torch.tensor(1)))) #np.exp(1)=e^1
print(torch.log10(torch.tensor(10)))
print(torch.log2(torch.tensor(2))) # log3 doesn't exist
print(torch.round(A))
print(torch.round(A,decimals=2)) # numpy doesn't need decimals in same structure
# print(torch.floor(A))
# print(torch.ceil(A))

tensor([[ 0.3401, -1.1585,  0.7835],
        [-0.0635, -0.3463,  0.1449],
        [ 1.6604, -0.1921,  1.3593]])
tensor([[0.3401, 1.1585, 0.7835],
        [0.0635, 0.3463, 0.1449],
        [1.6604, 0.1921, 1.3593]])
tensor([[0.5832, 1.0763, 0.8851],
        [0.2520, 0.5884, 0.3806],
        [1.2886, 0.4383, 1.1659]])
tensor([[1.4051, 0.3140, 2.1891],
        [0.9384, 0.7073, 1.1559],
        [5.2617, 0.8252, 3.8935]])
tensor([[-1.0785,  0.1471, -0.2440],
        [-2.7563, -1.0605, -1.9321],
        [ 0.5071, -1.6498,  0.3070]])
tensor(1.)
tensor(1.)
tensor(1.)
tensor([[ 0., -1.,  1.],
        [-0., -0.,  0.],
        [ 2., -0.,  1.]])
tensor([[ 0.3400, -1.1600,  0.7800],
        [-0.0600, -0.3500,  0.1400],
        [ 1.6600, -0.1900,  1.3600]])


In [ ]:
print(torch.sin(torch.tensor(torch.pi/6)))
print(torch.cos(torch.tensor(torch.pi/3)))
print(torch.tan(torch.tensor(torch.pi/4)))
print(torch.tanh(torch.tensor(-10)))

type(torch.pi) # torch pi's data type is float
type(torch.tensor(3.14)*6) # Data type is tensor

tensor(0.5000)
tensor(0.5000)
tensor(1.)
tensor(-1.)


torch.Tensor

In [ ]:
torch.nan # not a number
print(torch.log(torch.tensor(-1))) # negative number is available
print(torch.isnan(torch.tensor([1,2,torch.nan,3,4])))
print(torch.isinf(torch.tensor([1,2,3,4,torch.inf])))

tensor(nan)
tensor([False, False,  True, False, False])
tensor([False, False, False, False,  True])


In [ ]:
A=torch.randn(3,4)
print(A)
print(torch.max(A))
print(torch.max(A,dim=0))
print(torch.max(A,dim=1))
print(torch.max(A,dim=0, keepdims=True))
print(torch.max(A,dim=1, keepdims=True))
print(torch.min(A))
print(torch.min(A,dim=0))
print(torch.min(A,dim=1))
print(torch.argmax(A)) # In mathmatics, argmax means that x value which has maximum value

tensor([[-0.7868,  0.2793,  1.7181,  0.7203],
        [ 1.0881,  1.3277,  0.4702, -1.4314],
        [-0.5160,  0.3706, -0.9286, -0.0671]])
tensor(1.7181)
torch.return_types.max(
values=tensor([1.0881, 1.3277, 1.7181, 0.7203]),
indices=tensor([1, 1, 0, 0]))
torch.return_types.max(
values=tensor([1.7181, 1.3277, 0.3706]),
indices=tensor([2, 1, 1]))
torch.return_types.max(
values=tensor([[1.0881, 1.3277, 1.7181, 0.7203]]),
indices=tensor([[1, 1, 0, 0]]))
torch.return_types.max(
values=tensor([[1.7181],
        [1.3277],
        [0.3706]]),
indices=tensor([[2],
        [1],
        [1]]))
tensor(-1.4314)
torch.return_types.min(
values=tensor([-0.7868,  0.2793, -0.9286, -1.4314]),
indices=tensor([0, 0, 2, 1]))
torch.return_types.min(
values=tensor([-0.7868, -1.4314, -0.9286]),
indices=tensor([0, 3, 2]))
tensor(2)


In [ ]:
a=torch.randn(6,1)
print(a)
a_sorted=torch.sort(a,dim=0)
print(a_sorted) # ascending

a=torch.randn(6,1)
print(a)
print(a.sort(dim=0))
print(a.sort(dim=0,descending=True))

print(torch.max(a))
print(a.max())
print(torch.abs(a))
print(a.abs())

tensor([[-1.1929],
        [ 0.5529],
        [ 0.9379],
        [ 2.2947],
        [-0.1441],
        [-1.5922]])
torch.return_types.sort(
values=tensor([[-1.5922],
        [-1.1929],
        [-0.1441],
        [ 0.5529],
        [ 0.9379],
        [ 2.2947]]),
indices=tensor([[5],
        [0],
        [4],
        [1],
        [2],
        [3]]))
tensor([[ 1.0621],
        [-1.7318],
        [ 1.0577],
        [-0.1839],
        [-0.8896],
        [ 0.7906]])
torch.return_types.sort(
values=tensor([[-1.7318],
        [-0.8896],
        [-0.1839],
        [ 0.7906],
        [ 1.0577],
        [ 1.0621]]),
indices=tensor([[1],
        [4],
        [3],
        [5],
        [2],
        [0]]))
torch.return_types.sort(
values=tensor([[ 1.0621],
        [ 1.0577],
        [ 0.7906],
        [-0.1839],
        [-0.8896],
        [-1.7318]]),
indices=tensor([[0],
        [2],
        [5],
        [3],
        [4],
        [1]]))
tensor(1.0621)
tensor(1.0621)
tensor([[1.0621],
        [1.731

In [ ]:
A=torch.randn(3,4)
print(A)
print(torch.sum(A))
print(torch.sum(A,dim=1))
print(torch.sum(A,dim=1,keepdims=True))
print(torch.mean(A))
print(torch.mean(A,dim=1))
print(torch.mean(A,dim=1,keepdims=True))
print(torch.std(A))

print(A.sum(dim=1, keepdims=True))
print(A.mean(dim=1, keepdims=True))
print(A.std())

tensor([[-0.0044,  2.1194,  1.7285, -1.7798],
        [-0.5319,  0.6957,  0.3818,  0.1703],
        [-1.3796,  0.9181,  0.6248,  0.6031]])
tensor(3.5460)
tensor([2.0637, 0.7158, 0.7664])
tensor([[2.0637],
        [0.7158],
        [0.7664]])
tensor(0.2955)
tensor([0.5159, 0.1790, 0.1916])
tensor([[0.5159],
        [0.1790],
        [0.1916]])
tensor(1.1298)
tensor([[2.0637],
        [0.7158],
        [0.7664]])
tensor([[0.5159],
        [0.1790],
        [0.1916]])
tensor(1.1298)


In [ ]:
A=torch.randint(1,5, size=(12,))
print(A)
print(A.shape)

B=A.reshape(2,2,3)
print(B)
print(B.ndim)

tensor([2, 4, 4, 1, 4, 4, 4, 3, 3, 1, 3, 1])
torch.Size([12])
tensor([[[2, 4, 4],
         [1, 4, 4]],

        [[4, 3, 3],
         [1, 3, 1]]])
3


In [ ]:
a=torch.tensor([1,2,3])
b=torch.tensor([2,2,3])
print(torch.sum(a*b))

a=a.reshape(3,1)
b=b.reshape(3,1)
print(a.transpose(1,0)@b)
print(a.permute(1,0)@b)
print(a.T@b)

A=torch.randn(4,3,6)
print(A.permute(0,2,1).shape)
print

tensor(15)
tensor([[15]])
tensor([[15]])
tensor([[15]])
torch.Size([4, 6, 3])


<function print>

In [ ]:
A=torch.arange(20)
print(A)
print(A.reshape(4,5))
print(A.reshape(4,-1).shape)
print(A.reshape(2,5,-1).shape)
print(A.reshape(2,-1,5).shape)
print(A.reshape(1,-1)) # row vector
print(A.reshape(-1,1).shape) # column vector

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])
tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])
torch.Size([4, 5])
torch.Size([2, 5, 2])
torch.Size([2, 2, 5])
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
         18, 19]])
torch.Size([20, 1])


In [ ]:
x=torch.randn(2,3,4,5,6)
print(x[1,2,:,:,:].shape)
print(x[1,2,...].shape)
print(x[:,:,:,:,3].shape)
print(x[...,3].shape)

torch.Size([4, 5, 6])
torch.Size([4, 5, 6])
torch.Size([2, 3, 4, 5])
torch.Size([2, 3, 4, 5])


In [ ]:
A=torch.ones((2,3,4))
B=torch.zeros((2,3,4))
C=torch.vstack([A,B])
D=torch.hstack([A,B])

E=torch.cat([A,B], dim=0)
F=torch.cat([A,B], dim=1)
G=torch.cat([A,B], dim=2)


print(C)
print(D)
print(E)
print(F)


tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([

In [ ]:
A =torch.randn(1,1,1,3,1,1,4,1)
print(A.squeeze().shape)

torch.Size([3, 4])


In [ ]:
A = torch.randn(3,4)
print(A.unsqueeze(dim=0).shape)
print(A.unsqueeze(dim=1).shape)
print(A.unsqueeze(dim=2).shape)
print(A.reshape(1,3,4))
print(A.reshape(3,1,4))
print(A.reshape(3,4,1))

torch.Size([1, 3, 4])
torch.Size([3, 1, 4])
torch.Size([3, 4, 1])
tensor([[[-0.2821, -1.0794,  0.8483,  0.8200],
         [-2.3368, -1.2595,  0.6587, -0.0833],
         [ 0.3624, -0.2321,  0.7070, -0.4803]]])
tensor([[[-0.2821, -1.0794,  0.8483,  0.8200]],

        [[-2.3368, -1.2595,  0.6587, -0.0833]],

        [[ 0.3624, -0.2321,  0.7070, -0.4803]]])
tensor([[[-0.2821],
         [-1.0794],
         [ 0.8483],
         [ 0.8200]],

        [[-2.3368],
         [-1.2595],
         [ 0.6587],
         [-0.0833]],

        [[ 0.3624],
         [-0.2321],
         [ 0.7070],
         [-0.4803]]])


In [ ]:
A=torch.ones(3,4)
B=torch.zeros(3,4)
A=A.unsqueeze(dim=0) # It's possible to extend dimension
B=B.unsqueeze(dim=0)
C=torch.cat([A,B], dim=0)
print(C)
print(C.shape)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
torch.Size([2, 3, 4])


In [ ]:
A=torch.tensor([[1,2],[3,4]])
B=A.clone()
B[0,0]=100

In [ ]:
A=torch.randn(5,7)
B=torch.randn(7,10)
C=A@B
print(C.shape)

A=torch.randn(32,5,7)
B=torch.randn(32,7,10)
C=A@B
print(C.shape)

torch.Size([5, 10])
torch.Size([32, 5, 10])


In [ ]:
A=torch.randn(32,5,7)
B=torch.randn(7,10)

C=A@B.repeat(32,1,1)
D=A@B
print(C.shape)
print(D.shape)

torch.Size([32, 5, 10])
torch.Size([32, 5, 10])


In [ ]:
A = torch.rand(2,3)
A_repeat=A.repeat(3,1,3,2)

## Numpy < - > Torch

In [ ]:
import numpy as np
import torch

a=np.array([1,2,3])
b=torch.tensor([1,2,3])
A=torch.tensor(a) #numpy->tensor
A=torch.from_numpy(a)

B=b.numpy() #np.array(b) #tensor->numpy
print(A)
print(B)

tensor([1, 2, 3])
[1 2 3]


## Auto grad in Torch which is used in Deep Learning

In [ ]:
x=torch.tensor([1.], requires_grad=True) # 1=integer , 1.0=float
print(x)

tensor([1.], requires_grad=True)


In [ ]:
x=torch.tensor([1.], requires_grad=True) # 1=integer , 1.0=float, if I need to differentiate, data type must be float
y=x**2
print(y) #PowBackward0 가 붙어 있다!

y.backward() # backward is differentiation and substitutes 'x' to differentiated y
print(x.grad) # x.grad is a substituted value after y.backward"
print(type(x.grad))

tensor([1.], grad_fn=<PowBackward0>)
tensor([2.])
<class 'torch.Tensor'>


In [ ]:
x=torch.tensor([1.],requires_grad=True)
y=x**2
print(y)
y.retain_grad() # This line makes y.grad

z=3*y
print(z)

z.backward() # z is differentiated by x, backward means chain rule
print(x.grad)
print(y.grad)

tensor([1.], grad_fn=<PowBackward0>)
tensor([3.], grad_fn=<MulBackward0>)
tensor([6.])
tensor([3.])


In [ ]:
x=torch.tensor([1.],requires_grad=True)
y=x**2
z=3*y

y.backward() # This line is operated without z
print(x.grad)

tensor([2.])


In [ ]:
x=torch.tensor([1.],requires_grad=True)
a=x**2
b=a+1
print(b)
c=b**2
c.backward()
print(x.grad)

tensor([2.], grad_fn=<AddBackward0>)
tensor([8.])


In [ ]:
x=torch.tensor([1.],requires_grad=True)
y=torch.tensor([1.],requires_grad=True)
z=2*x**2 + y**2
print(z)
z.backward()
print(z.backward)
print(x.grad)
print(y.grad)

tensor([3.], grad_fn=<AddBackward0>)
<bound method Tensor.backward of tensor([3.], grad_fn=<AddBackward0>)>
tensor([4.])
tensor([2.])


In [ ]:
x=torch.tensor([1., 2., 3.],requires_grad=True)
y=torch.sum(x**2) #x1**2+x2**2+x3**2
y.backward()

print(y)
print(x.grad)

tensor(14., grad_fn=<SumBackward0>)
tensor([2., 4., 6.])


In [ ]:
x=torch.tensor([1.],requires_grad=True)
x.requires_grad=False # y.backward=error
#In transfer learning, x.requires_grad has to be False

In [ ]:
x=torch.tensor([1.],requires_grad=True)
with torch.no_grad(): #In torch.no_grad, requires_grad is maintained with True but detach 'grad' in y
    y=x**2
    print(x.requires_grad)
    print(y)
print(x.requires_grad)
y=x**2
print(y)

True
tensor([1.])
True
tensor([1.], grad_fn=<PowBackward0>)


In [ ]:
pip install torchviz

  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.7/23.7 MB 40.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 823.6/823.6 kB 45.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.1/14.1 MB 52.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 731.7/731.7 MB 689.7 kB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 410.6/410.6 MB 2.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.6/121.6 MB 6.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.5/56.5 MB 8.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.2/124.2 MB 6.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 196.0/196.0 MB 2.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 166.0/166.0 MB 2.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.1/99.1 kB 10.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 