<a href="https://colab.research.google.com/github/sokhan1/PYTHON/blob/main/Summary_Pytorch_(2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Simple ANN design

In [ ]:
import torch
from torch import nn

x=torch.tensor([1.]) # Integer is not available
model = nn.Linear(1,1) #the number of input node is 1  and the number of output node is 1

print(model.weight) #randomly set (initailization)
print(model.bias) #randomly set

y = model(x) # ANN is function
print(y)

y= x @ model.weight + model.bias
print(y)

Parameter containing:
tensor([[0.9354]], requires_grad=True)
Parameter containing:
tensor([-0.4086], requires_grad=True)
tensor([0.5268], grad_fn=<ViewBackward0>)
tensor([0.5268], grad_fn=<AddBackward0>)


In [ ]:
fc1=nn.Linear(1,3) #the number of input node is 1  and the number of output node is 3
fc2=nn.Linear(3,1) #fully connected layer

print(fc1.weight)
print(fc1.bias)
print(fc2.weight)
print(fc2.bias)

x=torch.tensor([1.])
x=fc1(x)
print(x)
x=fc2(x)
print(x)

x=torch.tensor([1.])
y=(x@fc1.weight.T+fc1.bias)@fc2.weight.T+fc2.bias # weight is needed to be transposed
#nn.Linear number x channel x row x column structure
# one node means one channel
#So, if you want to pass multiple pieces of data , you arrange data as 개x채
# Why? > We want to make 'W(weight)' 개x채
# In nn.Linear(2,3)

Parameter containing:
tensor([[-0.8625],
        [-0.1058],
        [-0.3274]], requires_grad=True)
Parameter containing:
tensor([ 0.6143,  0.2319, -0.5113], requires_grad=True)
Parameter containing:
tensor([[-0.5512,  0.3204, -0.4715]], requires_grad=True)
Parameter containing:
tensor([-0.1284], requires_grad=True)
tensor([-0.2482,  0.1261, -0.8387], grad_fn=<ViewBackward0>)
tensor([0.4442], grad_fn=<ViewBackward0>)


In [ ]:
fc1= nn.Linear(1,3)
fc2= nn.Linear(3,1)

model = nn.Sequential(fc1,fc2) #Combine layers(fc1,fc2)
x=torch.tensor([1.])
print(model(x))

tensor([-0.6754], grad_fn=<ViewBackward0>)


In [ ]:
model=nn.Sequential(nn.Linear(2,5),
              nn.Linear(5,10),
              nn.Linear(10,3))

x=torch.randn(2)
print(x)
print(model(x))

x=torch.randn(5,2) # number and channel(human and attribute)
print(x)
print(model(x))

tensor([-0.3111,  1.6899])
tensor([0.3624, 0.1591, 0.0616], grad_fn=<ViewBackward0>)
tensor([[-0.8134,  0.5658],
        [-0.8865,  1.8012],
        [ 0.0473, -1.5728],
        [-0.1315,  0.3152],
        [ 0.7159, -1.1441]])
tensor([[ 0.1978,  0.0533,  0.1814],
        [ 0.3234,  0.1543,  0.0905],
        [ 0.0453, -0.1036,  0.2908],
        [ 0.2313,  0.0492,  0.1563],
        [ 0.1503, -0.0514,  0.2140]], grad_fn=<AddmmBackward0>)


In [ ]:
class MyModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1=nn.Linear(2,5)
        self.fc2=nn.Linear(5,10)
        self.fc3=nn.Linear(10,3)
        self.sig1 = nn.Sigmoid()
        self.sig2 = nn.Sigmoid()
        self.sig3 = nn.Sigmoid()
    def forward(self, x):
        x=self.fc1(x)
        x=self.sig1(x)
        x=self.fc2(x)
        x=self.sig2(x)
        x=self.fc3(x)
        x=self.sig3(x)
        return x

model = MyModel()
x= torch.randn(5,2)
y= model(x)
print(y)

tensor([[0.7035, 0.6382, 0.5230],
        [0.6982, 0.6360, 0.5332],
        [0.7023, 0.6376, 0.5251],
        [0.7002, 0.6375, 0.5298],
        [0.7038, 0.6399, 0.5233]], grad_fn=<SigmoidBackward0>)


In [ ]:
print(model)
print(model.fc1.weight) # See weights
print(model.fc1.bias) # See biases

MyModel(
  (fc1): Linear(in_features=2, out_features=5, bias=True)
  (fc2): Linear(in_features=5, out_features=10, bias=True)
  (fc3): Linear(in_features=10, out_features=3, bias=True)
  (sig1): Sigmoid()
  (sig2): Sigmoid()
  (sig3): Sigmoid()
)
Parameter containing:
tensor([[-0.4925,  0.6604],
        [ 0.0425,  0.0037],
        [ 0.0042,  0.4552],
        [ 0.2691,  0.3812],
        [-0.6589,  0.2528]], requires_grad=True)
Parameter containing:
tensor([-0.4362, -0.1811, -0.1945, -0.4412, -0.1912], requires_grad=True)


In [ ]:
class MyModel2(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear=nn.Sequential(
            nn.Linear(2,5),
            nn.Sigmoid(),
            nn.Linear(5,10),
            nn.Sigmoid(),
            nn.Linear(10,3),
            nn.Sigmoid()
        )
    def forward(self, x):
        x=self.linear(x)
        return x

model2 = MyModel2()
x= torch.randn(5,2)
y= model2(x)
print(y)

tensor([[0.4793, 0.5111, 0.4691],
        [0.4796, 0.5134, 0.4691],
        [0.4794, 0.5114, 0.4700],
        [0.4794, 0.5124, 0.4685],
        [0.4794, 0.5113, 0.4697]], grad_fn=<SigmoidBackward0>)


In [ ]:
print(model2)
print(model2.linear)
print(model2.linear[0])
print(model2.linear[1])
print(model2.linear[2])

MyModel2(
  (linear): Sequential(
    (0): Linear(in_features=2, out_features=5, bias=True)
    (1): Sigmoid()
    (2): Linear(in_features=5, out_features=10, bias=True)
    (3): Sigmoid()
    (4): Linear(in_features=10, out_features=3, bias=True)
    (5): Sigmoid()
  )
)
Sequential(
  (0): Linear(in_features=2, out_features=5, bias=True)
  (1): Sigmoid()
  (2): Linear(in_features=5, out_features=10, bias=True)
  (3): Sigmoid()
  (4): Linear(in_features=10, out_features=3, bias=True)
  (5): Sigmoid()
)
Linear(in_features=2, out_features=5, bias=True)
Sigmoid()
Linear(in_features=5, out_features=10, bias=True)


In [ ]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.2668,  0.4528],
         [-0.0248, -0.0416],
         [ 0.2409,  0.0687],
         [-0.2019, -0.0400],
         [-0.4205, -0.2866]], requires_grad=True),
 Parameter containing:
 tensor([0.3972, 0.3566, 0.1112, 0.3657, 0.1818], requires_grad=True),
 Parameter containing:
 tensor([[-0.1643, -0.3019, -0.0097, -0.0201, -0.2843],
         [ 0.2599, -0.1076, -0.1175, -0.3714,  0.3312],
         [ 0.2843, -0.0513, -0.2641,  0.2006,  0.3257],
         [-0.3541,  0.4018,  0.0270,  0.1535, -0.4008],
         [-0.0430,  0.0533,  0.2453, -0.2566, -0.1694],
         [-0.4339,  0.2084, -0.2180,  0.0534,  0.2528],
         [ 0.1238,  0.2439, -0.4328,  0.1623, -0.1073],
         [ 0.3011,  0.1690, -0.0266, -0.1168, -0.3447],
         [-0.0943, -0.3550, -0.0401,  0.0936,  0.0517],
         [ 0.0243,  0.0120, -0.1972, -0.3773, -0.0253]], requires_grad=True),
 Parameter containing:
 tensor([-0.0799,  0.1542, -0.2812,  0.0175,  0.2532, -0.0866, -0.0645, -0.3803,
       

In [ ]:
[p for p in model.parameters()]
[p.numel() for p in model.parameters()]
sum([p.numel() for p in model.parameters()]) # the number of parameters
sum([p.numel() for p in model.parameters() if p.requires_grad]) #the number of training parameters (except for hyperparameter)

108