<a href="https://colab.research.google.com/github/sokhan1/PYTHON/blob/main/Tensorflow_Practice_of_me.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Start of Tensorflow


In [2]:
import numpy as np
import tensorflow as tf

In [3]:
print(tf.__version__)

2.17.0


##텐서(Tensor)의 객체


*   Type: string, float32, float16, int32, int8 등
*   Shape: 0,1,2차원 등의 데이터 차원
*   Rank: 차원의 갯수





In [4]:
a = tf.constant(2)
print(tf.rank(a))
print(a)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


In [5]:
b = tf.constant([2,3])
print(tf.rank(b))
print(b)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor([2 3], shape=(2,), dtype=int32)


In [6]:
c = tf.constant([[2,3],[6,7]])
print(tf.rank(c))
print(c)

tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(
[[2 3]
 [6 7]], shape=(2, 2), dtype=int32)


In [7]:
d = tf.constant(['hello'])
print(tf.rank(d))
print(d)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor([b'hello'], shape=(1,), dtype=string)


## Generate random numbers

In [8]:
rand1 = tf.random.uniform([1],0,1)
print(rand1.shape)
print(rand1)

(1,)
tf.Tensor([0.41163933], shape=(1,), dtype=float32)


In [9]:
rand2 = tf.random.normal([1,2],0,1)
print(rand2.shape)
print(rand2)

(1, 2)
tf.Tensor([[-0.6894357  0.8112462]], shape=(1, 2), dtype=float32)


In [10]:
rand3 = tf.random.normal(shape=(3,2), mean=0, stddev=1)
print(rand3.shape)
print(rand3)

(3, 2)
tf.Tensor(
[[ 1.3337009 -0.2848974]
 [-0.7143665  2.1781   ]
 [-1.161617  -1.0727443]], shape=(3, 2), dtype=float32)


##즉시 실행 모드(Eager Mode)지원
*   즉시 실행모드를 통해 텐서플로우를 파이썬처럼 사용할 수 있음
*   1.x 버전에서는 '그래프'를 생성하고, 초기화 한 뒤에 세션을 통해 값을 흐르게 하는 작업을 진행해야함



In [11]:
a = tf.constant(3)
b = tf.constant(2)

In [12]:
print(tf.add(a,b))
print(a+b)

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)


In [13]:
print(tf.subtract(a,b))
print(a-b)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)


In [14]:
print(tf.multiply(a,b))
print(a*b)

tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)


##텐서 플로우 <-> 넘파이
*   numpy()
*   tf.convet_to_tensor()

In [15]:
c = (a+b).numpy()
print(c)
print(type(c))

5
<class 'numpy.int32'>


In [16]:
[1,2,3]
(1,2,3)

(1, 2, 3)

In [17]:
c_sqrt = np.sqrt(c, dtype=np.float32)
c_tensor = tf.convert_to_tensor(c_sqrt)
print(c_tensor)
print(type(c_tensor))

tf.Tensor(2.236068, shape=(), dtype=float32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


##Use like a numpy

In [18]:
t = tf.constant([[1.,2.,3.],[4.,5.,6.]])
print(t.shape)
print(t.dtype)

(2, 3)
<dtype: 'float32'>


In [19]:
print(t[:,1:])

tf.Tensor(
[[2. 3.]
 [5. 6.]], shape=(2, 2), dtype=float32)


In [20]:
t+10

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[11., 12., 13.],
       [14., 15., 16.]], dtype=float32)>

In [21]:
t @ tf.transpose(t)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

## 타입 변환
*   연산시 텐서의 타입을 맞춰줘야 함
    *   float32 ~ float32
    *   int32 ~ int32
    *   float32 ~ int32
*   타입변환에는 tf.cast()사용








In [23]:
a = tf.constant(2)
print(a)

b=tf.constant(2.)
print(b)

tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(2.0, shape=(), dtype=float32)


In [27]:
t=tf.constant(2.0, dtype=tf.float64) #float64
t2 = tf.constant(2.) # float32
t3 = t + tf.cast(t2, dtype=tf.float64)

print(t3)
print(type(t3))

tf.Tensor(4.0, shape=(), dtype=float64)
<class 'tensorflow.python.framework.ops.EagerTensor'>


##AutoGraph


*   Tensorflow가 작업을 좀 더 빠르게 동작하게 하기 위한 방법으로 Graph로 만들어 연산을 진행
*   tf.Graph
*   flexible
    *   모바일 애플리케이션, 임베디드 기기, 백엔드 서버와 같이 Python 인터프러터가 없는 환경에서 Tensorflow 사용 가능









In [28]:
import timeit

###@tf.function


*   Generate graph automatically
*   그래프로 변환하여 사용 ->GPU 연산 가능
*   파이썬으로 구성된 함수를 텐서플로우의 그래프 형태로 다루고 싶을 때 사용가능
*   Original Function (tf.function).python_function()



In [29]:
@tf.function
def my_function(x):
    return x**2 - 10*x +3

print(my_function(2))
print(my_function(tf.constant(2)))

tf.Tensor(-13, shape=(), dtype=int32)
tf.Tensor(-13, shape=(), dtype=int32)


In [30]:
def my_function(x):
    return x**2 - 10*x +3

print(my_function(2))
print(my_function(tf.constant(2)))

-13
tf.Tensor(-13, shape=(), dtype=int32)
