<a href="https://colab.research.google.com/github/sokhan1/PYTHON/blob/main/Tensorflow_Practice_of_me.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Start of Tensorflow


In [1]:
import numpy as np
import tensorflow as tf

In [2]:
print(tf.__version__)

2.17.0


##텐서(Tensor)의 객체


*   Type: string, float32, float16, int32, int8 등
*   Shape: 0,1,2차원 등의 데이터 차원
*   Rank: 차원의 갯수





In [3]:
a = tf.constant(2)
print(tf.rank(a))
print(a)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


In [4]:
b = tf.constant([2,3])
print(tf.rank(b))
print(b)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor([2 3], shape=(2,), dtype=int32)


In [5]:
c = tf.constant([[2,3],[6,7]])
print(tf.rank(c))
print(c)

tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(
[[2 3]
 [6 7]], shape=(2, 2), dtype=int32)


In [6]:
d = tf.constant(['hello'])
print(tf.rank(d))
print(d)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor([b'hello'], shape=(1,), dtype=string)


## Generate random numbers

In [7]:
rand1 = tf.random.uniform([1],0,1)
print(rand1.shape)
print(rand1)

(1,)
tf.Tensor([0.2815212], shape=(1,), dtype=float32)


In [8]:
rand2 = tf.random.normal([1,2],0,1)
print(rand2.shape)
print(rand2)

(1, 2)
tf.Tensor([[-0.41524482  0.8904816 ]], shape=(1, 2), dtype=float32)


In [9]:
rand3 = tf.random.normal(shape=(3,2), mean=0, stddev=1)
print(rand3.shape)
print(rand3)

(3, 2)
tf.Tensor(
[[-0.24439333  0.35521245]
 [ 0.52555615 -0.7875333 ]
 [-1.9718934  -1.4290195 ]], shape=(3, 2), dtype=float32)


##즉시 실행 모드(Eager Mode)지원
*   즉시 실행모드를 통해 텐서플로우를 파이썬처럼 사용할 수 있음
*   1.x 버전에서는 '그래프'를 생성하고, 초기화 한 뒤에 세션을 통해 값을 흐르게 하는 작업을 진행해야함



In [10]:
a = tf.constant(3)
b = tf.constant(2)

In [11]:
print(tf.add(a,b))
print(a+b)

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)


In [12]:
print(tf.subtract(a,b))
print(a-b)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)


In [13]:
print(tf.multiply(a,b))
print(a*b)

tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)


##텐서 플로우 <-> 넘파이
*   numpy()
*   tf.convet_to_tensor()

In [14]:
c = (a+b).numpy()
print(c)
print(type(c))

5
<class 'numpy.int32'>


In [15]:
[1,2,3]
(1,2,3)

(1, 2, 3)

In [16]:
c_sqrt = np.sqrt(c, dtype=np.float32)
c_tensor = tf.convert_to_tensor(c_sqrt)
print(c_tensor)
print(type(c_tensor))

tf.Tensor(2.236068, shape=(), dtype=float32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


##Use like a numpy

In [17]:
t = tf.constant([[1.,2.,3.],[4.,5.,6.]])
print(t.shape)
print(t.dtype)

(2, 3)
<dtype: 'float32'>


In [18]:
print(t[:,1:])

tf.Tensor(
[[2. 3.]
 [5. 6.]], shape=(2, 2), dtype=float32)


In [19]:
t+10

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[11., 12., 13.],
       [14., 15., 16.]], dtype=float32)>

In [20]:
t @ tf.transpose(t)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

## 타입 변환
*   연산시 텐서의 타입을 맞춰줘야 함
    *   float32 ~ float32
    *   int32 ~ int32
    *   float32 ~ int32
*   타입변환에는 tf.cast()사용








In [21]:
a = tf.constant(2)
print(a)

b=tf.constant(2.)
print(b)

tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(2.0, shape=(), dtype=float32)


In [22]:
t=tf.constant(2.0, dtype=tf.float64) #float64
t2 = tf.constant(2.) # float32
t3 = t + tf.cast(t2, dtype=tf.float64)

print(t3)
print(type(t3))

tf.Tensor(4.0, shape=(), dtype=float64)
<class 'tensorflow.python.framework.ops.EagerTensor'>


##AutoGraph


*   Tensorflow가 작업을 좀 더 빠르게 동작하게 하기 위한 방법으로 Graph로 만들어 연산을 진행
*   tf.Graph
*   flexible
    *   모바일 애플리케이션, 임베디드 기기, 백엔드 서버와 같이 Python 인터프러터가 없는 환경에서 Tensorflow 사용 가능









In [23]:
import timeit

###@tf.function


*   Generate graph automatically
*   그래프로 변환하여 사용 ->GPU 연산 가능
*   파이썬으로 구성된 함수를 텐서플로우의 그래프 형태로 다루고 싶을 때 사용가능
*   Original Function (tf.function).python_function()



In [24]:
@tf.function
def my_function(x):
    return x**2 - 10*x +3

print(my_function(2))
print(my_function(tf.constant(2)))

tf.Tensor(-13, shape=(), dtype=int32)
tf.Tensor(-13, shape=(), dtype=int32)


In [25]:
def my_function(x):
    return x**2 - 10*x +3

print(my_function(2))
print(my_function(tf.constant(2)))

-13
tf.Tensor(-13, shape=(), dtype=int32)


In [26]:
tf_my_function = tf.function(my_function)
print(tf_my_function(2))
print(tf_my_function.python_function(2))

tf.Tensor(-13, shape=(), dtype=int32)
-13


In [27]:
def function_to_get_faster(x,y,b):
    x = tf.matmul(x,y)
    x = x + b
    return x

a_function_that_uses_a_graph = tf.function(function_to_get_faster)

x1=tf.constant([[1.,2.]])
y1=tf.constant([[2.],[3.]])
b1=tf.constant(4.)

print(x1.shape)
print(y1.shape)

a_function_that_uses_a_graph(x1,y1,b1).numpy()

(1, 2)
(2, 1)


array([[12.]], dtype=float32)

In [28]:
def inner_function(x,y,b):
    x = tf.matmul(x,y)
    x = x + b
    return x

@tf.function
def outer_function(x):
    y = tf.constant([[2.],[3.]])
    b = tf.constant(4.)
    return inner_function(x,y,b)

outer_function(tf.constant([[1.,2.]])).numpy()

array([[12.]], dtype=float32)

### Improvement of speed

In [31]:
class SequentialModel(tf.keras.Model):
    def __init__(self, **kwargs):
        super(SequentialModel, self).__init__(**kwargs)
        self.flatten = tf.keras.layers.Flatten(input_shape=(28,28))
        self.dense_1 = tf.keras.layers.Dense(128, activation = 'relu')
        self.dropout = tf.keras.layers.Dropout(0,2)
        self.dense_2 = tf.keras.layers.Dense(10)

    def call(self, x):
        x = self.flatten(x)
        x = self.dense_1(x)
        x = self.dropout(x)
        x = self.dense_2(x)
        return x

input_data = tf.random.uniform([60,28,28])

eager_model = SequentialModel()
graph_model = tf.function(eager_model)

print(f"Eager time:{timeit.timeit(lambda: eager_model(input_data), number=10000)}")
print(f"Graph time:{timeit.timeit(lambda: graph_model(input_data), number=10000)}")



/usr/local/lib/python3.10/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Eager time:40.55919046100007
Graph time:13.525212491000275


###변수 생성


*   tf.Variable
*   딥러닝 모델 학습 시, 그래픈 연산이 필요할 때 사용



In [32]:
X = tf.Variable(20.)

print(X)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=20.0>


### Autograd(자동 미분)


*   tf.GradientTape API 사용
*   tf.Variable 같은 일부 입력에 대한 기울기 계산
  *   기본적으로 한번만 사용됨
*   변수가 포함된 연산만 기록



In [41]:
x = tf.Variable(3.)
with tf.GradientTape() as tape:
    y = x**2

In [42]:
print(type(x))
print(type(y))

<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [39]:
dy_dx = tape.gradient(y,x)
print(dy_dx)
dy_dx.numpy()

tf.Tensor(6.0, shape=(), dtype=float32)


6.0

RuntimeError: A non-persistent GradientTape can only be used to compute one set of gradients (or jacobians)