<a href="https://colab.research.google.com/github/sokhan1/PYTHON/blob/main/Tensorflow_Practice_of_me.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Start of Tensorflow


In [1]:
import numpy as np
import tensorflow as tf

In [2]:
print(tf.__version__)

2.17.0


##텐서(Tensor)의 객체


*   Type: string, float32, float16, int32, int8 등
*   Shape: 0,1,2차원 등의 데이터 차원
*   Rank: 차원의 갯수





In [3]:
a = tf.constant(2)
print(tf.rank(a))
print(a)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


In [4]:
b = tf.constant([2,3])
print(tf.rank(b))
print(b)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor([2 3], shape=(2,), dtype=int32)


In [6]:
c = tf.constant([[2,3],[6,7]])
print(tf.rank(c))
print(c)

tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(
[[2 3]
 [6 7]], shape=(2, 2), dtype=int32)


In [7]:
d = tf.constant(['hello'])
print(tf.rank(d))
print(d)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor([b'hello'], shape=(1,), dtype=string)


## Generate random numbers

In [8]:
rand1 = tf.random.uniform([1],0,1)
print(rand1.shape)
print(rand1)

(1,)
tf.Tensor([0.55277085], shape=(1,), dtype=float32)


In [9]:
rand2 = tf.random.normal([1,2],0,1)
print(rand2.shape)
print(rand2)

(1, 2)
tf.Tensor([[ 0.118095  -1.4382905]], shape=(1, 2), dtype=float32)


In [10]:
rand3 = tf.random.normal(shape=(3,2), mean=0, stddev=1)
print(rand3.shape)
print(rand3)

(3, 2)
tf.Tensor(
[[-1.8024054  -0.64345807]
 [ 0.08281001  0.7668122 ]
 [-0.00706843 -0.51604277]], shape=(3, 2), dtype=float32)
